const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  doc: [
    'overview',
    'getting-started',
    {
      type: 'link',
      label: 'API Quick Reference',
      href: 'https://pkg.go.dev/gitlab.com/elixxir/client/xxdk',
    },
    {
      type: 'category',
      label: 'Mobile Docs',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'mobile docs/ios-sdk',
      ],
    },
    'technical-glossary',
  ],
};

module.exports = sidebars;
